"""Committed structured Stage 01 handoffs.

Each fixture is an **accepted** Stage 01 output: a `RequirementSpec` that carries
the structured fields Stage 02 requires, including `BehaviourSpec`. They are
committed so the deterministic suite can test the Stage 01 -> Stage 02 contract
without a model call and without the incomplete producer.

They are not generated by `IncompleteRequirementProducer`, which emits no
behaviour and cannot satisfy the contract by construction.
"""

from __future__ import annotations

import json
from pathlib import Path

from assy.domain.upstream import RequirementSpec

FIXTURE_DIR = Path(__file__).parent / "fixtures"
BENCHMARK_IDS = ("BM-001", "BM-002", "BM-101")


def load_spec(benchmark_id: str) -> RequirementSpec:
    """A fresh, independently mutable spec for one benchmark."""
    raw = json.loads((FIXTURE_DIR / f"{benchmark_id}_requirementspec.json").read_text())
    return RequirementSpec.model_validate(raw)


def all_specs() -> dict[str, RequirementSpec]:
    return {bid: load_spec(bid) for bid in BENCHMARK_IDS}


def fingerprint(arch) -> dict:
    """Everything Stage 02 decided, in a comparable form.

    Object ids are excluded deliberately: they are minted per run and would mask
    a real equality with a spurious difference.
    """
    return {
        "selected_id": arch.selected_id,
        "candidates": sorted(c.id for c in arch.candidates),
        "chains": {c.id: list(c.element_chain) for c in arch.candidates},
        "functions": {
            c.id: [(f.function, list(f.performed_by)) for f in c.functions]
            for c in arch.candidates
        },
        "obligations": {
            c.id: [(o.element, o.kind.value, o.reacted_by) for o in c.support_obligations]
            for c in arch.candidates
        },
        "interfaces": {
            c.id: [(list(i.between), i.kind.value, i.crosses_boundary) for i in c.interfaces]
            for c in arch.candidates
        },
        "constrained_by": {c.id: sorted(c.constrained_by) for c in arch.candidates},
        "traceability": {c.id: sorted(c.serves_requirements) for c in arch.candidates},
        "holding": {c.id: c.holding_principle for c in arch.candidates},
        "rejected": dict(arch.rejected),
        "rationale": arch.selection_rationale,
        "advisories": sorted(arch.contract_advisories),
    }


def deficiency_fingerprint(deficiency) -> dict:
    return {
        "items": sorted(
            (d.missing_field, d.requirement_id, d.blocking) for d in deficiency.items
        )
    }
